### ISSUE TITLE
is it possible to read overlay pxiel data in the future?

### ISSUE THREAD

**Issue by AngYu** [dgobbi/vtk-dicom#129]
as title.

**Comment by dgobbi** [comment]
Yes, I had always planned to support overlays.  I can add a GetOverlayOutput(int i=0) method to get the overlay data from the reader.  This is something that I can probably find time for in the next two weeks.

**Comment by dgobbi** [comment]
Overlay loading is now in the master branch (1353b5a through a649521).

The primary methods are GetOverlayOutput() and GetOverlayOutputPort().
Also see Examples/TestDICOMOverlay.cxx

The overlays are loaded as an 8-bit image (or a 16-bit image if more than 8 overlays are present).
