### ISSUE TITLE
Cannot load vtkDICOM in java when using GDCM or ITK_GDCM

### ISSUE THREAD

**Issue by YiiGuxing** [dgobbi/vtk-dicom#159]
java.lang.UnsatisfiedLinkError: no vtkDICOMJava in java.library.path
    	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    	at java.lang.System.loadLibrary(System.java:1122)
    	at vtk.vtkNativeLibrary.LoadLibrary(vtkNativeLibrary.java:241)
        ...

Other VTK dynamic libraries are loadable

**Comment by dgobbi** [comment]
What operating system are you using?  I've tested vtkDICOM + Java + GDCM on Linux so far.

**Comment by YiiGuxing** [comment]
Windows 10 x64
VTK-8.1.2
GDCM-2.8.8-Windows-x86_64 or InsightToolkit-4.13.1
Visual Studio 15 2017 Win64

**Comment by dgobbi** [comment]
I'll be able to test your configuration tomorrow.
Have you tried building GDCM as a static library?

**Comment by YiiGuxing** [comment]
Yes. I tried building to dynamic and static library, but they didn't work.

**Comment by YiiGuxing** [comment]
Failed to build vtkDICOM.dll when using DCMTK.
Is my configuration wrong?
![image](https://user-images.githubusercontent.com/10737066/48691203-a4983000-ec0c-11e8-95a9-d44a629781b5.png)

**Comment by YiiGuxing** [comment]
Can be loaded after restarting the operating system.
I'm sorry, this is my fault.

**Comment by dgobbi** [comment]
That, in itself, is useful information.  Thanks for the follow-up.
