### ISSUE TITLE
Compressed DICOM

### ISSUE THREAD

**Issue by eidelen** [dgobbi/vtk-dicom#161]
Hi,
We use vtk-dicom in our software. First of all, thanks a lot for the great work.
One of our users [reported an issue ](https://github.com/AOT-AG/DicomToMesh/issues/14)that he was not able to load a data set. I looked at it, and it seems that vtk-dicom fails because the DICOM is compressed:
```
ERROR: In /vtk-dicom/Source/vtkDICOMReader.cxx, line 1885
vtkDICOMReader (0x7f8749e00840): DICOM file is compressed, cannot read.
```
We use vtk-dicom in a simple way:
```
vtkSmartPointer<vtkDICOMReader> reader = vtkSmartPointer<vtkDICOMReader>::New();
reader->SetFileNames( fileName );
reader->Update();
```
Can we solve that with vtk-dicom?

Thank you,
Adrian

**Comment by dgobbi** [comment]
Compressed files will work with vtk-dicom, but only if vtk-dicom is configured and built with the USE\_GDCM option turned on.  This is because vtk-dicom relies on the gdcm libraries for decompression.  More info here: http://dgobbi.github.io/vtk-dicom/doc/api/installation.html

**Comment by eidelen** [comment]
That worked. Thank you!
