### ISSUE TITLE
Enhancement: add progress text to reader

### ISSUE THREAD

**Issue by efahl** [dgobbi/vtk-dicom#162]
Some of our end users read datasets across a slow network (say, Australia or India reading from central US).  Our old reader called `vtkDICOMImageReader.GetProgressText` to fetch the name of the specific file being read, which we then display in status, thus giving the users a sense that something was being accomplished while they sip their coffee.

`vtkDICOMReader` appears to be missing this bit, so I hacked a call to `SetProgressText` into the read method and that seems to work exactly as the old ImageReader scheme, but I'm pretty tentative as to the appropriateness of this change...

```
bool vtkDICOMReader::ReadOneFile(
  const char *filename, int fileIdx,
  unsigned char *buffer, vtkIdType bufferSize)
{
  this->SetProgressText(filename);
```

**Comment by dgobbi** [comment]
Well, I wouldn't want to dull the users' sense of accomplishment when they stare at the computer screen with a cup of coffee in hand.

Progress text is a good idea, so I have implemented it in a5903496.  Thanks for the suggestion!
