### ISSUE TITLE
python module import error on installation (vs build)

### ISSUE THREAD

**Issue by C-nit** [dgobbi/vtk-dicom#163]
I'm building vtk from source on windows with vtk-dicom as a remote module.

Everything seems fine after **ALL_BUILD**, as `import vtk` has the dicom classes.  
In this case I had put the VTK_BUILD_PYTHON_MODULE_DIR and the directory with the .dlls and .pyd (e.g. build_dir/bin/Release) on the PYTHONPATH 

However when I build the **INSTALL** target, I get an import error:
```python
import vtk
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\VTK\lib\python3.6\site-packages\vtk\vtkDICOM.py in <module>()
      4     # use relative import for installed modules
----> 5     from .vtkDICOMPython import *
      6 except ImportError:

ImportError: DLL load failed: The specified module could not be found.
```
This occurs after successfully loading other vtk python modules, with PYTHONPATH including the installed bin/ path (.dll and cli-tools) and VTK_INSTALL_PYTHON_MODULE_DIR ( vtk/\*.py and \*Python.pyd )
To be clear, the vtkDICOM\*.dll and \*.pyd are all there split in the respective directories.

What is going wrong on the INSTALL target?

Btw:
adding to the PYTHONPATH is easily done via [a .pth file](https://docs.python.org/3/install/index.html#modifying-python-s-search-path) under the environments site-packages directory

**Comment by C-nit** [comment]
Great tool; thanks for the link!

I didn't build with USE_GDCM or USE_DCMTK to start with.
The dependencies of the vtkDICOM.dll from the build step seem to be identical to that of the install. Just different locations of the dependencies, nothing seems to be missing.

I put the .dll on the PATH now (e.g. C:\VTK\bin) and the vtk import works like that.
However that seems to be a workaround considering that only vtkDICOM requires this.
Or is this expected behavior?

**Comment by dgobbi** [comment]
Okay, so it doesn't seem to be a dependency issue.  I'm away from my PC for the next two weeks, so I can't check the DLL install locations myself, but just to confirm:

After you do a make install, can you tell me where each of these DLLs is located?
1) vtkCommonCore.dll and the other VTK C++ dlls
2) vtkCommonCorePythonD.dll and the other *Python.dlls
3) vtkDICOM.dll and vtkDICOMPythonD.dll
4) vtkDICOMPython.pyd and vtkCommonCorePython.pyd

**Comment by C-nit** [comment]
under C:\VTK\bin there are 1., 2., 3.:
- vtkCommonCore-8.1.dll, vtkDICOM-8.1.dll and all other C++
- vtkCommonCorePython36D-8.1.dll, vtkDICOMPython36D-8.1.dll and all other Python
all DLLs are named with versions as seen above.

under C:\VTK\lib\python3.6\site-packages\vtk is 4.:
- vtkDICOMPython.pyd, vtkCommonCorePython.pyd, and all other .pyd

**Comment by dgobbi** [comment]
In an earlier message you said:

> I put the .dll on the PATH now (e.g. C:\VTK\bin) and the vtk import works like that.

So now I'm confused.  Did the DLLs go into VTK\\bin when you built the INSTALL target, or did you copy them there yourself?

**Comment by C-nit** [comment]
They were moved there on INSTALL.
I meant that I added C:\VTK\bin to the PATH environment variable.
