### ISSUE TITLE
Error while enabling the vtkDICOM module in VTK 8.2.0

### ISSUE THREAD

**Issue by chenjianyyzz** [dgobbi/vtk-dicom#169]
I try to enable the vtkDICOM module in VTK 8.2.0, I set the Module vtkDICOM option for the cmake cache:
    cmake -D Module_vtkDICOM :BOOL=ON …/vtk -source
then I got the warning:
CMake Warning:
   Manually-specified variables were not used by the project:
         Module_vtkDICOM

does anybody know how to handle this?
thanks

**Comment by dgobbi** [comment]
Try this:

    cmake -D Module_vtkDICOM=ON ../vtk-source

What operating system are you using?

**Comment by dgobbi** [comment]
You will also need to apply the following fix to the VTK source:

https://gitlab.kitware.com/vtk/vtk/commit/0a90fe94
