### ISSUE TITLE
dicom segment object

### ISSUE THREAD

**Issue by pdeman** [dgobbi/vtk-dicom#170]
Hi,

is it possible using vtk-dicom to generate a dicom from a tiff (the raw data) and it's associated dicom segment object which contains some segmentation done on it ?

Regards,

**Comment by dgobbi** [comment]
DICOM segmentation objects can be read by vtk-dicom, but cannot be written.   You might want to look at the segmentation object support in 3D Slicer:
https://dicom4qi.readthedocs.io/en/latest/results/seg/3dslicer/
http://perk.cs.queensu.ca/contents/polymorph-segmentation-representation-medical-image-computing
