### ISSUE TITLE
Could not find a package configuration file provided by "VTK" with ...

### ISSUE THREAD

**Issue by IgorDePaula** [dgobbi/vtk-dicom#177]
![Captura de tela de 2019-09-04 13-49-55](https://user-images.githubusercontent.com/2833993/64275034-0ebf5e80-cf1b-11e9-8b1d-90f6fe0b0395.png)
[CMakeOutput.log](https://github.com/dgobbi/vtk-dicom/files/3575636/CMakeOutput.log)

**Comment by dgobbi** [comment]
Which version of VTK are you using?  For VTK 8.2 or earlier, then the above should work if VTK\_DIR is set.

For VTK master, then it is necessary to build vtk-dicom as a "remote module" by adding `VTK_MODULE_ENABLE_VTK_vtkDICOM=WANT` to VTK's cmake configuration.

**Comment by IgorDePaula** [comment]
VTK version? None, I'm tring install vtk-dicom, is necessary install vtk before? I don't know. I'll install now.

I tried insta, but I received error:

![Captura de tela de 2019-09-04 14-59-36 - 1](https://user-images.githubusercontent.com/2833993/64279179-d3c22880-cf24-11e9-9fdb-f7e95fa245ca.png)

**Comment by IgorDePaula** [comment]
I install vtk7 by repositories.

**Comment by dgobbi** [comment]
Do you want to use vtk-dicom to develop VTK applications?  If you only want the vtk-dicom [command-line tools](https://github.com/dgobbi/vtk-dicom/wiki/Command-Line-Tools) then you can [download them from the releases page](https://github.com/dgobbi/vtk-dicom/releases).

The `Could NOT find OpenGL` error means that cmake needs the OpenGL dev packages:

    sudo apt-get install libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

**Comment by IgorDePaula** [comment]
I would like transform dicom images to obj or glTF.  I'm try install this lib because it is a dependency to https://github.com/AOT-AG/DicomToMesh
