### ISSUE TITLE
dicomdump leading spaces for sequences with multiple values or JSON

### ISSUE THREAD

**Issue by computationdoc** [dgobbi/vtk-dicom#190]
dicomdump is excellent, but to feed it into another tool besides just human reading, a formal tree structure would be great enhancement.

Each level of the tree doesn't have a closing statement per se - the use case is each directory with all the files in a DICOM study (we have many of those), so it works well to create a complete text description of each study for human reading but nontrivial (as demonstrated in example below) parsing would be required to ingest it.

Ingesting each of those DICOM study files from a dicomdump to a formal tree structure like a JSON of the whole study, is not straightforward for a couple reasons.

1. There is no "mark" to close a tree level. Prefer the whole output as a big JSON so I don't have to parse and be concerned about possible edge cases (such as 2 below). (not formal DICOM json structure for each file, that is a different JSON).

2. In some cases the spacing structure may be degenerate: when a tag is both a sequence and multiple values there isn't extra spacing for each sub-sequence. Having that would at least be a bit easier to parse, without concern for possible other edge cases like this that require "carrying" the "state" of a particular line in the file (not just its relation to lines above and below it), even though still not "closing mark" per se, it could be figured out a bit easier. Because of this concern I'm not sure of other edge cases, so while "fixing" this would be good, JSON would be even better (as noted in 1 above) so I don't have to.

I am not up to reading your code, but It would seem to me somewhere in the process of the current dicomdump, this whole tree must exist, and could be "dumped" in a formal tree structure in a text file (e.g. JSON).

Here is an example output of possibly degenerate case (with some values redacted and leading spaces replaced with X to make them easier to "see" - always 2 spaces except first and last line whereas it would seem some could have 4 spaces to "properly tree").

(0008,2112) SQ "SourceImageSequence" : (multiple values)
XX0001 (1 item)
XX---- SQ Item 0001 at offset 1124 ----
XX(0008,1150) UI "ReferencedSOPClassUID" : [1.2.840.10008.5.1.4.1.1.12.1] {X-Ray Angiographic Image Storage} (28 bytes)
XX(0008,1155) UI "ReferencedSOPInstanceUID" : [REDACTED] (62 bytes)
XX(0008,1160) IS "ReferencedFrameNumber" : [1] (2 bytes)
XX0002 (1 item)
XX---- SQ Item 0001 at offset 1124 ----
XX(0008,1150) UI "ReferencedSOPClassUID" : [1.2.840.10008.5.1.4.1.1.12.1] {X-Ray Angiographic Image Storage} (28 bytes)
XX(0008,1155) UI "ReferencedSOPInstanceUID" : [REDACTED] (62 bytes)
XX(0008,1160) IS "ReferencedFrameNumber" : [1] (2 bytes)
(0010,0010) PN "PatientName" : [REDACTED] (10 bytes)

**Comment by dgobbi** [comment]
Thanks for your comments. Indeed, the data is stored in a tree and eventually I would like to enhance dicomdump so that it can produce json (#135).  If it's something that you need in the near term, then please contact me by email and we might be able to work something out.
