### ISSUE TITLE
VTK/Examples/Cxx/IO/ReadDICOMSeries error

### ISSUE THREAD

**Issue by papadonik** [dgobbi/vtk-dicom#193]
Hello, I am a beginner. I am using the ReadDicomSeries in Blender for surgical planning. I am getting the following error. when trying to open a directory that contains DICOM files that I want to scroll

ERROR: In C:\Users\papad\Downloads\VTK-8.2.0\VTK-8.2.0\IO\Image\vtkDICOMImageReader.cxx, line 270
vtkDICOMImageReader (000002C180226B40): There was a problem retrieving data from: C:\Users\papad\Downloads\DICOM_anonymized\DICOM_anonymized\unnamed - 3\

ERROR: In C:\Users\papad\Downloads\VTK-8.2.0\VTK-8.2.0\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkCompositeDataPipeline (000002C1801E20B0): Algorithm vtkDICOMImageReader(000002C180226B40) returned failure for request: vtkInformation (000002C1801FEA70)
  Debug: Off
  Modified Time: 128
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

Any help on how to solve the use or use the VTK DICOM instead would be greatly appreciated. Thank you

**Comment by dgobbi** [comment]
You probably either passed a directory via SetFileName(), or the directory that you passed via SetDirectory() has subdirectories.
