### ISSUE TITLE
NG building from microsoft/vcpkg 

### ISSUE THREAD

**Issue by QiuKejian** [dgobbi/vtk-dicom#196]
build vtk-dicom from vcpkg, find_package and target_link_libraries is not working.

The following find_package and target_link_libraries is not working.
![image](https://user-images.githubusercontent.com/12969818/89864181-15039380-dbde-11ea-975a-cc0a228aed0c.png)

Error Message is: LINK: fatal error LNK1104: can not open "VTK::DICOM.lib".

Check the vcpkg build log , we can find that vtk-dicom is built by "outside of VTK" mode.
![image](https://user-images.githubusercontent.com/12969818/89864988-7b3ce600-dbdf-11ea-81c3-531eee97ffec.png)

Please help, How can I fix this problem?

**Comment by JackBoosY** [comment]
Related: https://github.com/microsoft/vcpkg/pull/12839

**Comment by dgobbi** [comment]
Which version of VTK are you using? Are you building programs that use vtk-dicom, or are you packaging it up for other people to use?

For VTK 9, the most common way to build vtkDICOM is to enable it as part of the VTK build itself, by using the following configuration option (only for VTK 9, not for older versions of VTK):

VTK_MODULE_ENABLE_VTK_DICOM:STRING=DEFAULT

For VTK 8 and earlier, the instructions at https://dgobbi.github.io/vtk-dicom/doc/api/installation.html should work.

**Comment by JackBoosY** [comment]
@dgobbi VTK version 9.0.1.
Use [official usage](https://dgobbi.github.io/vtk-dicom/doc/api/installation.html):
```
find_package(DICOM QUIET)
if(DICOM_FOUND)
  include(${DICOM_USE_FILE})
endif()
set(VTK_DICOM_LIBRARIES vtkDICOM)
```
does't work.

**Comment by QiuKejian** [comment]
> Which version of VTK are you using? Are you building programs that use vtk-dicom, or are you packaging it up for other people to use?
> 
> For VTK 9, the most common way to build vtkDICOM is to enable it as part of the VTK build itself, by using the following configuration option (only for VTK 9, not for older versions of VTK):
> 
> VTK_MODULE_ENABLE_VTK_DICOM:STRING=DEFAULT
> 
> For VTK 8 and earlier, the instructions at https://dgobbi.github.io/vtk-dicom/doc/api/installation.html should work.

**Comment by QiuKejian** [comment]
> Which version of VTK are you using? Are you building programs that use vtk-dicom, or are you packaging it up for other people to use?
> 
> For VTK 9, the most common way to build vtkDICOM is to enable it as part of the VTK build itself, by using the following configuration option (only for VTK 9, not for older versions of VTK):
> 
> VTK_MODULE_ENABLE_VTK_DICOM:STRING=DEFAULT
> 
> For VTK 8 and earlier, the instructions at https://dgobbi.github.io/vtk-dicom/doc/api/installation.html should work.

appreciate for reply！！
I was using VTK9, the latest version. The situation is that I had build VTK9.0.1 from vcpkg, 
therefore vtk-dicom is built outside of VTK.

On the other hand, i am trying to build vtk-dicom as a sub module, in this case there is also an unexpected behavior.
![image](https://user-images.githubusercontent.com/12969818/90006005-b1a35f80-dcca-11ea-9e50-8933b0bc8a6a.png)


The reason is:
![image](https://user-images.githubusercontent.com/12969818/90006070-cc75d400-dcca-11ea-8561-f382a12a557f.png)
