### ISSUE TITLE
Dicom Dir folder adress

### ISSUE THREAD

**Issue by emmanuels7** [dgobbi/vtk-dicom#198]
Hi. 

Is it possible to obtain the dicom dir folder as an adittional column in `dicomtcsv`?

Regards

**Comment by dgobbi** [comment]
With `-k ReferencedFileID`, dicomtocsv will give the path to the first file in the series, but that's the closest it will come to giving the folder.  You can use `--default` to use the default dicomtocsv query and add `ReferencedFileID` at the end:

    dicomtocsv --default -k ReferencedFileID
