### ISSUE TITLE
Possible to have any python example?

### ISSUE THREAD

**Issue by 1939938853** [dgobbi/vtk-dicom#208]
Hi,

I have just built vtk-dicom with VTK 9.1 and Python 3.9. The `__init__.py` has only one line code as 
`
__all__ = ['vtkDICOM']
`
I don't know if it is correct. Perhaps it is good to provide some Python example to test and start with?

Thank you!

**Comment by dgobbi** [comment]
That's correct.  The vtkdicom package contains one module called vtkDICOM, and the vtkDICOM module contains all of the classes.

As with all python packages, it either has to be in PYTHONPATH or in Python's `site-packages` directory.

```python
from vtkdicom.vtkDICOM import vtkDICOMReader
```

**Comment by 1939938853** [comment]
Hi,

I just ran `  from vtkdicom.vtkDICOM import vtkDICOMReader ` but got `Process finished with exit code 5

Empty suite`. Might be a empty python wrapping?

**Comment by dgobbi** [comment]
Can you give me some information about your system?

1. operating system (Windows, Linux, etc)
2. which version of Python you're using
3. info about the Python environment (e.g. is this in Anaconda, or PyCharm, etc.)
4. which version of VTK was used
5. what compiler was used to build VTK and vtk-dicom

**Comment by 1939938853** [comment]
Hello, 

I'm using

Windows 10, VS2019, VTK 9.1, Pycharm python interpreter is the same as build VTK python wrapper and vtk-dicom wrapper that is Python 3.9 in conda base.  Pycharm python interpreter added path to both vtk/build/bin/Lib/site-packages  and vtk-dicom/build/bin/Lib/site-packages. I also copied vtkDICOM-9.1.dll to vtk-dicom\build\bin\Lib\site-packages\vtkdicom folder.

Thanks

**Comment by dgobbi** [comment]
Thanks for the info.  My guess is that vtkDICOM-9.1.dll is not able to see the other VTK dlls.  Can you try calling `add_dll_directory()` before importing vtkDICOM?

```python
import os
handle1 = os.add_dll_directory("/path/to/VTK/DLLs")

from vtkdicom.vtkDICOM import vtkDICOMReader
```
Unfortunately, I don't use either conda or PyCharm, so I can't help much with them.
