### ISSUE TITLE
Bug in vtkDICOMReader.cxx at Line 2511 

### ISSUE THREAD

**Issue by retinexpt** [dgobbi/vtk-dicom#213]
This is a nice DICOM parser and I use it in my project.

There may be a bug at Line 2511 in vtkDICOMReader.cxx.  The input arguments of the function AddWindowLevelPreset should be swapped. Namely,
original:
          

>  properties->AddWindowLevelPreset(    center.GetDouble(i), width.GetDouble(i));

fixed:
           properties->AddWindowLevelPreset(    width.GetDouble(i), center.GetDouble(i));

**Comment by dgobbi** [comment]
Thanks for the report.  I've pushed the fix to the master branch.
