### ISSUE TITLE
VS 2020 compile issue

### ISSUE THREAD

**Issue by inglis-dl** [dgobbi/vtk-dicom#216]
debug static build tag branch v0.8.9 against static VTK 9.1.0.  VS solution missing include of installed vtk.  ZLIB not found but forced use of
vtkzlib.  Seeing the following errors in VS after manual add of installed vtk include path:

Build started...
1>------ Build started: Project: vtkDICOM, Configuration: Debug x64 ------
1>vtkDICOMMetaData.cxx
1>vtkDICOMDictionary.cxx
1>vtkDICOMFilePath.cxx
1>vtkDICOMFile.cxx
1>vtkDICOMFileDirectory.cxx
1>vtkDICOMTag.cxx
1>vtkDICOMTagPath.cxx
1>vtkDICOMVR.cxx
1>vtkDICOMVM.cxx
1>vtkDICOMCharacterSet.cxx
1>vtkDICOMCharacterSetTables.cxx
1>vtkDICOMDataElement.cxx
1>vtkDICOMDictHash.cxx
1>vtkDICOMDictEntry.cxx
1>vtkDICOMDictPrivate.cxx
1>vtkDICOMDirectory.cxx
1>C:\code\repository\vtk-dicom\Source\vtkDICOMDirectory.cxx(959,5): error C2143: syntax error: missing ';' before 'return'
1>C:\code\repository\vtk-dicom\Source\vtkDICOMDirectory.cxx(990,5): error C2143: syntax error: missing ';' before 'return'
1>vtkDICOMFileSorter.cxx
1>C:\code\repository\vtk-dicom\Source\vtkDICOMFileSorter.cxx(221,3): error C2143: syntax error: missing ';' before '}'
1>vtkDICOMGenerator.cxx
1>vtkDICOMImageCodec.cxx
1>vtkDICOMSCGenerator.cxx
1>Generating Code...
1>Compiling...
1>vtkDICOMCTGenerator.cxx
1>vtkDICOMMRGenerator.cxx
1>vtkDICOMParser.cxx
1>vtkDICOMCompiler.cxx
1>vtkDICOMReader.cxx
1>vtkDICOMSliceSorter.cxx
1>vtkDICOMSequence.cxx
1>vtkDICOMItem.cxx
1>vtkDICOMSorter.cxx
1>vtkDICOMReferenceCount.cxx
1>vtkDICOMUtilities.cxx
1>vtkDICOMUtilitiesUIDTable.cxx
1>vtkDICOMValue.cxx
1>vtkDICOMWriter.cxx
1>vtkDICOMAlgorithm.cxx
1>vtkDICOMLookupTable.cxx
1>vtkDICOMApplyPalette.cxx
1>vtkDICOMApplyRescale.cxx
1>vtkDICOMToRAS.cxx
1>vtkDICOMCTRectifier.cxx
1>Generating Code...
1>Compiling...
1>vtkDICOMMetaDataAdapter.cxx
1>vtkDICOMUIDGenerator.cxx
1>vtkNIFTIHeader.cxx
1>vtkNIFTIReader.cxx
1>vtkNIFTIWriter.cxx
1>vtkScancoCTReader.cxx
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.h(219,21): error C2061: syntax error: identifier 'ifstream'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.h(222,21): error C2061: syntax error: identifier 'ifstream'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(179,3): error C2065: 'ifstream': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(179,12): error C2146: syntax error: missing ';' before identifier 'infile'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(179,12): error C3861: 'infile': identifier not found
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(182,7): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(186,5): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(187,10): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(194,3): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(412,38): error C2065: 'ifstream': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(412,48): error C2065: 'file': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(412,54): error C2062: type 'unsigned long' unexpected
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(413,1): error C2143: syntax error: missing ';' before '{'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(413,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(623,38): error C2065: 'ifstream': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(623,48): error C2065: 'file': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(623,54): error C2062: type 'unsigned long' unexpected
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(624,1): error C2143: syntax error: missing ';' before '{'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(624,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(990,3): error C2065: 'ifstream': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(990,12): error C2146: syntax error: missing ';' before identifier 'infile'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(990,12): error C3861: 'infile': identifier not found
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(991,8): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1001,3): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1004,8): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1006,44): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1014,5): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1021,40): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1025,40): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1028,3): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1118,3): error C2065: 'ifstream': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1118,12): error C2146: syntax error: missing ';' before identifier 'infile'
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1118,12): error C3861: 'infile': identifier not found
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1119,8): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1127,3): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1157,5): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1164,5): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1174,5): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1178,29): error C2065: 'infile': undeclared identifier
1>C:\code\repository\vtk-dicom\Source\vtkScancoCTReader.cxx(1186,3): error C2065: 'infile': undeclared identifier
1>Generating Code...
1>Done building project "vtkDICOM.vcxproj" -- FAILED.
2>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 1 skipped =========

**Comment by dgobbi** [comment]
Hi Dean,

The compile errors in vtkDICOMDirectory and vtkDICOMFileSorter were fixed by fdee452a.
The compile errors in vtkScancoCTReader were fixed by d15c9b91.

The latest release (v0.8.13) contains both of these fixes.

**Comment by inglis-dl** [comment]
working now with v0.8.13, thank you
