### ISSUE TITLE
Hello, can you update the latest version to vcpkg?

### ISSUE THREAD

**Issue by MikeKen-Ken** [dgobbi/vtk-dicom#217]
The version of vcpkg is 8.0.12, which is too old, and have some bug when install by vcpkg. So I need the latest version

I really appreciate you if you can upgrade.

Thank you

**Comment by dgobbi** [comment]
The vcpkg is maintained at https://github.com/microsoft/vcpkg, or more specifically the version is set in https://github.com/microsoft/vcpkg/blob/master/versions/baseline.json .  You can check there to see if they can pull a newer version.
