### ISSUE TITLE
Missing find_package(dcmtk) in dicom-config.cmake?

### ISSUE THREAD

**Issue by RobertHabrich** [dgobbi/vtk-dicom#232]
Hi.

I have successfully build vtk-dicom with `USE_DCMTK` enabled. I was now trying to consume the built vtk-dicom library via `find_package(dicom REQUIRED)` and `target_link_libraries(myapp VTK::DICOM)` using the cmake scripts installed to {CMAKE_INSTALL_PREFIX}/lib/cmake/dicom-0.8. This currently fails with:

```
The link interface of target "VTK::DICOM" contains:

    dcmtk::dcmtk

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

It seems like a `find_package(dcmtk)` is missing? I can make it work by manually calling that on my side beforehand:
```
find_package(dcmtk REQUIRED)
find_package(dicom REQUIRED)
```

But it should most likely be done in dicom-config.cmake.in similar to ITK/GDCM ([here](https://github.com/dgobbi/vtk-dicom/blob/master/CMake/dicom-config.cmake.in#L41))?

**Comment by dgobbi** [comment]
Thanks for the note, I've added DCMTK to dicom-config.cmake.  But I still need to update the machinery a bit, I originally wrote the code assuming the now-obsolete "FindDCMTK.cmake".

**Comment by RobertHabrich** [comment]
Another problem I've run into when trying to integrate the library via find_package into an actual project: The name "dicom" might be a bit too generic. My project also has a static lib called "dicom" and that now clashes, e.g. my `find_package(dicom REQUIRED)` call is only looking for my own static library.

Have not yet found out the exact underlying problem. My guess is that both my dicom library's binary dir as well as vtk-dicom's {INSTALL_DIR}/lib/cmake/dicom-0.8 directory are in the search path. But I hope that CMake somehow allows me to resolve this for now.

**Comment by RobertHabrich** [comment]
> Another problem I've run into when trying to integrate the library via find_package into an actual project: The name "dicom" might be a bit too generic. My project also has a static lib called "dicom" and that now clashes, e.g. my `find_package(dicom REQUIRED)` call is only looking for my own static library.
> 
> Have not yet found out the exact underlying problem. My guess is that both my dicom library's binary dir as well as vtk-dicom's {INSTALL_DIR}/lib/cmake/dicom-0.8 directory are in the search path. But I hope that CMake somehow allows me to resolve this for now.

Forgot to update my ramblings here... our environment is a bit more complex since we are having a bunch of dependencies that are all deployed via conan (incl. vtk-dicom). As suspected above, the conflict was that we have an internal library named "dicom" for which conan generates cmake scripts to find the package. The path to these scripts as well as the path to the vtk-dicom config files is in cmake's prefix path. So when later calling `find_package(dicom)` stuff is not really going to work out.

My guess is that there is a way to rename the scripts that conan generates for our internal dicom library and avoid the conflict like that. However, I'm actually patching the vtk-dicom provided cmake scripts during deployment (renaming them to "vtk-dicom")...

So in the end there is no real request to change anything in this project here.

**Comment by dgobbi** [comment]
Adding `find_package(DCMTK)` before `find_package(DICOM)` doesn't cause any cmake warnings for me.  I'm using cmake 3.22.

On your end, can you try deleting vtk-dicom/CMake/FindDCMTK.cmake to see if it makes any difference?  It shouldn't, because this FindDCMTK is only used for the configuration of vtk-dicom itself, and not for packages that use vtk-dicom.

**Comment by RobertHabrich** [comment]
Yes, the custom FindDCMTK.cmake file is actually not the cause at all.

I'm somewhat certain what the issue is but need to investigate it further. It should not have anything to do with vtk-dicom at all.
We are using a [conan package for dcmtk](https://conan.io/center/recipes/dcmtk?version=3.6.8) which in turn does not seem to use the default FindDCMTK.cmake provided by CMake itself but generates its own, which in turn seems to result in these warning when another package (e.g. vtk-dicom) then uses the default FindDCMTK script.

**Comment by dgobbi** [comment]
Then it should be possible to silence the warning by adding `set(DCMTK_FOUND 1)` before `find_package(DICOM)`.
