### ISSUE TITLE
dcmtk codec registration/cleanup multithreading issues

### ISSUE THREAD

**Issue by RobertHabrich** [dgobbi/vtk-dicom#235]
Currently, vtkDICOMReader always registers dcmtk codecs in its [constructor](https://github.com/dgobbi/vtk-dicom/blob/4ea84f1884b9bcb050d351379c2e4769a9a3cf85/Source/vtkDICOMReader.cxx#L127) and cleans them up in the [destructor](https://github.com/dgobbi/vtk-dicom/blob/master/Source/vtkDICOMReader.cxx#L140) (conditional only based on the `DICOM_USE_DCMTK` macro). This works fine for single-threaded usage of vtkDICOMReader. However, when multiple different vtkDICOMReader instances can be used simultaneously in different threads, the cleanup call can easily lead to crashes, since dcmtk just checks a static boolean here (set to true in the register calls) and deletes data that is still in use (see e.g. [here](https://github.com/DCMTK/dcmtk/blob/d1fb197927fd4178b5a24e0f0dba6f8d785a8f93/dcmdata/libsrc/dcrledrg.cc#L54) for RLE codec).

Perhaps an option to disable the automatic registration/cleanup is possible so that it can be done by the consumer?

**Comment by dgobbi** [comment]
Yup, I put the codec registration in the reader because it was an expedient thing to do, but it really is tidier to do it at the application level.  I'll add a reference count (atomic) to deal with threads and expose methods to allow the registration/cleanup to be controlled manually.

**Comment by dgobbi** [comment]
I've pushed 8971919 to the master branch to fix the thread-safety issues and to allow the application to call `vtkDICOMReader::RegisterCodecs()/UnRegisterCodecs()` directly.  It doesn't yet provide a way to disable the registration completely, but it does allow greater control.

**Comment by dgobbi** [comment]
The new release (v0.8.17) should be thread-safe with respect to concurrently using readers in different threads.  Feel free to re-open this issue if the problem persists.
