### ISSUE TITLE
make error when use vtkSmartPointer<vtkNIFTIReader>

### ISSUE THREAD

**Issue by vinllen** [dgobbi/vtk-dicom#47]
Hi, all:
I have a problem when use your lib. I use cmake and make to install the lib into my source file. But when i cmake && make my project, there comes an error:

CMakeFiles/nlmFilter.dir/process.cpp.o: In function `vtkSmartPointer<vtkNIFTIReader>::New()':
/usr/local/include/vtk-5.10/vtkSmartPointer.h:113: undefined reference to `vtkNIFTIReader::New()'
collect2: error: ld returned 1 exit status
make[2]: *** [nlmFilter] Error 1
make[1]: *** [CMakeFiles/nlmFilter.dir/all] Error 2
make: *** [all] Error 2

Even when i use 
vtkSmartPointer<vtkNIFTIReader> reader = vtkSmartPointer<vtkNIFTIReader>::New();
or 
vtkNIFTIReader reader = vtkNIFTIReader::New();
I cannot pass the make, does anybody kown?

**Comment by dgobbi** [comment]
Hi Vinllen, if it is an undefined reference error, then you might be missing the target_link_libraries() call in your CMakeLists.txt file.  The following is an example of using vtk-dicom from another project:

    # Find vtk-dicom
    find_package(DICOM QUIET)
    if(DICOM_FOUND)
      include(${DICOM_USE_FILE})
    endif(DICOM_FOUND)

    # Link your program to the vtkDICOM library
    target_link_libraries(YourProgram vtkDICOM)

**Comment by vinllen** [comment]
Thankyou dgobbi!
